<a href="https://colab.research.google.com/github/Kaini9/Data-Analytics-Training/blob/main/Pandas/Assignment/10_Counting_PracticeQns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Final Practice — 10 Titanic Counting Questions

### Q1. Count the total number of passengers in the Titanic dataset.

### Q2. Count how many male and female passengers are present.

### Q3. Count how many passengers belong to each `Pclass`.

### Q4. Count how many passengers survived and how many died.

### Q5. Count how many passengers have missing `Age` values.

### Q6. Count how many passengers have missing `Cabin` values.

### Q7. Count how many passengers are male and survived.

### Q8. Count the total number of passengers for each `Embarked` value.

### Q9. Count passengers for every `Pclass` and `Sex` combination using `groupby().size()`.

### Q10. Create a cross-tabulation showing `Sex` against `Survived`.

LETS IMPORT THE PANDAS AND THE DATASET

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/titanic_dataset.csv")
df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
265,266,0,2,"Reeves, Mr. David",male,36.0,0,0,C.A. 17248,10.5000,NaN,S
500,501,0,3,"Calic, Mr. Petar",male,17.0,0,0,315086,8.6625,NaN,S

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     1309 non-null   int64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB

Q1. Count the total number of passengers in the Titanic dataset.

In [4]:
df["PassengerId"].count()

np.int64(1309)

### Q2. Count how many male and female passengers are present.

In [8]:
df.groupby("Sex").size()

Sex
female    466
male      843
dtype: int64

### Q3. Count how many passengers belong to each `Pclass`

In [9]:
df.groupby("Pclass").size()

Pclass
1    323
2    277
3    709
dtype: int64

## Q4. Count how many passengers survived and how many died.

In [10]:
df.groupby("Survived").size()

Survived
0    815
1    494
dtype: int64

### Q5. Count how many passengers have missing `Age` values.

In [14]:
df["Age"].isnull().sum()

np.int64(263)

### Q6. Count how many passengers have missing `Cabin` values.

In [16]:
df["Cabin"].isnull().sum()

np.int64(1014)


### Q7. Count how many passengers are male and survived.

shape[0], it counts row of selected column and conditions

In [32]:
df.loc[(df["Sex"]=="male") & (df["Survived"]==1)].shape[0]

109

### Q8. Count the total number of passengers for each `Embarked` value.

In [36]:
df.groupby("Embarked").size()

Embarked
C    270
Q    123
S    914
dtype: int64


### Q9. Count passengers for every `Pclass` and `Sex` combination using `groupby().size()`.

In [37]:
df.groupby(["Pclass","Sex"]).size()

Pclass  Sex
1       female    144
        male      179
2       female    106
        male      171
3       female    216
        male      493
dtype: int64

### Q10. Create a cross-tabulation showing `Sex` against `Survived`.

In [39]:
pd.crosstab(df["Sex"], df["Survived"])

Survived    0    1
Sex
female     81  385
male      734  109