<a href="https://colab.research.google.com/github/Kaini9/Data-Analytics-Training/blob/main/Pandas/Assignment/Dummy_dataset_create.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd

In [21]:
import pandas as pd
import random

first_names = list(dict.fromkeys([
    "saval","Rohan","Anish","Suman","Bibek","Prabin","Nischal","Sagar","Roshan","Aayush",
    "Bikash","Sandesh","Sujan","Kiran","Nabin","Rajesh","Ramesh","Ashish","Manish","Dipesh",
    "Rahul","Suraj","Samir","Sandeep","Prakash","Pawan","Niraj","Rajan","Arjun","Amit",
    "Anil","Sunil","Santosh","Binod","Bimal","Dinesh","Deepak","Rupesh","Suresh","Siddharth",
    "Sophia","Emma","Olivia","Ava","Mia","Isabella","Emily","Charlotte","Amelia","Harper",
    "Evelyn","Ella","Grace","Chloe","Lily","Aria","Zoe","Hannah","Maya","Sofia",
    "Liam","Noah","Oliver","James","William","Henry","Lucas","Benjamin","Theodore","Jack",
    "Daniel","Michael","Alexander","Matthew","Joseph","David","Samuel","John","Owen","Leo"
]))

last_names = [
    "kaini","Thapa","Karki","Gurung","Shrestha","Rai","Tamang","KC","Adhikari","Poudel",
    "Bhandari","Gautam","Basnet","Bhattarai","Maharjan","Lama","Magar","Rana","Joshi","Dahal",
    "Khanal","Acharya","Regmi","Pandey","Bista","Bohara","Chaudhary","Yadav","Mishra","Singh",
    "Johnson","Smith","Williams","Brown","Jones","Miller","Davis","Wilson","Taylor","Anderson",
    "Thomas","Moore","Martin","Jackson","White","Harris","Clark","Lewis","Young","Walker"
]

job_titles = [
    "Data Analyst","Software Engineer","Business Analyst","Data Scientist",
    "HR Manager","Marketing Analyst","Financial Analyst","Project Manager",
    "Web Developer","QA Engineer"
]

In [22]:
random.seed(42)
all_names = list({f"{first} {last}" for first in first_names for last in last_names})
random.shuffle(all_names)
names = all_names[:1050]

df = pd.DataFrame({
    "id": range(1, 1051),
    "name": names,
    "salary": [random.randint(30000, 150000) for _ in range(1050)],
    "job_title": [random.choice(job_titles) for _ in range(1050)]
})

df.to_csv("company_data_1050.csv", index=False)

In [23]:

print("total data:", len(df))
print("duplicate checking:", df["name"].duplicated().sum())
df

total data: 1050
duplicate checking: 0

        id              name  salary          job_title
0        1       Binod Clark  130969       Data Analyst
1        2  Matthew Williams   57215       Data Analyst
2        3   Prabin Bhandari   89233  Software Engineer
3        4      Olivia Davis   70410  Financial Analyst
4        5   Rajesh Bhandari   90731    Project Manager
...    ...               ...     ...                ...
1045  1046       Chloe Yadav  107846   Business Analyst
1046  1047        Jack Young   36286    Project Manager
1047  1048  Prakash Shrestha  116765  Financial Analyst
1048  1049       Aria Bohara   44170     Data Scientist
1049  1050      Lily Johnson  115664  Financial Analyst

[1050 rows x 4 columns]

In [20]:
df.head(4)

   id              name  salary          job_title
0   1       Binod Clark  130969       Data Analyst
1   2  Matthew Williams   57215       Data Analyst
2   3   Prabin Bhandari   89233  Software Engineer
3   4      Olivia Davis   70410  Financial Analyst

In [ ]:
df.describe()

                id         salary
count  1050.000000    1050.000000
mean    525.500000   90354.660000
std     303.253195   35246.989026
min       1.000000   30089.000000
25%     263.250000   59286.250000
50%     525.500000   89900.500000
75%     787.750000  121277.750000
max    1050.000000  149822.000000